/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sayfalar;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Salih Degirmenci
 */
public class Anasayfa extends javax.swing.JFrame {

    /**
     * Creates new form Anasayfa
     */
    public Anasayfa(){
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton_kitap_ekle = new javax.swing.JButton();
        kitaplar_img = new javax.swing.JLabel();
        odunc_al = new javax.swing.JLabel();
        teslim_et_img = new javax.swing.JLabel();
        jButton_kitaplar = new javax.swing.JButton();
        jButton_odunc_al = new javax.swing.JButton();
        jButton_teslim_et = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        kapat = new javax.swing.JLabel();
        kucult = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));
        jPanel1.setForeground(new java.awt.Color(255, 0, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        jButton_kitap_ekle.setBackground(java.awt.Color.orange);
        jButton_kitap_ekle.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton_kitap_ekle.setText("Kitap Ekle");
        jButton_kitap_ekle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_kitap_ekle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_kitap_ekleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_kitap_ekleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_kitap_ekleMouseExited(evt);
            }
        });
        jButton_kitap_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_kitap_ekleActionPerformed(evt);
            }
        });

        jButton_kitaplar.setBackground(java.awt.Color.orange);
        jButton_kitaplar.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton_kitaplar.setText("Kitaplar");
        jButton_kitaplar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_kitaplar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_kitaplarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_kitaplarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_kitaplarMouseExited(evt);
            }
        });
        jButton_kitaplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_kitaplarActionPerformed(evt);
            }
        });

        jButton_odunc_al.setBackground(java.awt.Color.orange);
        jButton_odunc_al.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton_odunc_al.setText("Ödünç Al");
        jButton_odunc_al.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_odunc_al.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_odunc_alMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_odunc_alMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_odunc_alMouseExited(evt);
            }
        });
        jButton_odunc_al.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_odunc_alActionPerformed(evt);
            }
        });

        jButton_teslim_et.setBackground(java.awt.Color.orange);
        jButton_teslim_et.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton_teslim_et.setText("Teslim Al");
        jButton_teslim_et.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_teslim_et.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_teslim_etMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_teslim_etMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_teslim_etMouseExited(evt);
            }
        });
        jButton_teslim_et.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_teslim_etActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 0, 153));

        kapat.setToolTipText("KAPAT");
        kapat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kapat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kapatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kapatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kapatMouseExited(evt);
            }
        });

        kucult.setToolTipText("Simge Durumuna");
        kucult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kucult.setName(""); // NOI18N
        kucult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kucultMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kucultMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kucultMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AYDINLAR KÜTÜPHANE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kucult, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(kucult, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kapat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/kapat.png")));
        kucult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/kucult.png")));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(odunc_al, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kitaplar_img, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jButton_kitaplar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(teslim_et_img, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton_teslim_et, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton_kitap_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_odunc_al, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(odunc_al, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_kitap_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_odunc_al, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kitaplar_img, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teslim_et_img, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_teslim_et, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_kitaplar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/book-closed.png")));
        kitaplar_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/book-shelf.png")));
        odunc_al.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/borrowing-take.png")));
        teslim_et_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/odunc-al.png")));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered

    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited

    }//GEN-LAST:event_jLabel2MouseExited

    private void jButton_kitap_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_kitap_ekleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_kitap_ekleActionPerformed

    private void jButton_kitap_ekleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_kitap_ekleMouseEntered
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/book-opened.png")));
        jButton_kitap_ekle.setForeground(Color.white);
        jButton_kitap_ekle.setBackground(new Color(153,0,153));
    }//GEN-LAST:event_jButton_kitap_ekleMouseEntered

    private void jButton_kitap_ekleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_kitap_ekleMouseExited
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/book-closed.png")));
        jButton_kitap_ekle.setForeground(new Color(0,0,0));
        jButton_kitap_ekle.setBackground(Color.orange);
    }//GEN-LAST:event_jButton_kitap_ekleMouseExited

    private void jButton_kitaplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_kitaplarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_kitaplarActionPerformed

    private void jButton_odunc_alActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_odunc_alActionPerformed
        
    }//GEN-LAST:event_jButton_odunc_alActionPerformed

    private void jButton_kitaplarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_kitaplarMouseEntered
        kitaplar_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/book-shelf2.png")));
        jButton_kitaplar.setForeground(Color.white);
        jButton_kitaplar.setBackground(new Color(153,0,153));
    }//GEN-LAST:event_jButton_kitaplarMouseEntered

    private void jButton_kitaplarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_kitaplarMouseExited
        kitaplar_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/book-shelf.png")));
        jButton_kitaplar.setForeground(new Color(0,0,0));
        jButton_kitaplar.setBackground(Color.orange);
    }//GEN-LAST:event_jButton_kitaplarMouseExited

    private void jButton_odunc_alMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_odunc_alMouseEntered
        odunc_al.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/borrowing-walking.png")));
        jButton_odunc_al.setForeground(Color.white);
        jButton_odunc_al.setBackground(new Color(153,0,153));
    }//GEN-LAST:event_jButton_odunc_alMouseEntered

    private void jButton_odunc_alMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_odunc_alMouseExited
        odunc_al.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/borrowing-take.png")));
        jButton_odunc_al.setForeground(new Color(0,0,0));
        jButton_odunc_al.setBackground(Color.orange);
    }//GEN-LAST:event_jButton_odunc_alMouseExited

    private void jButton_teslim_etMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_teslim_etMouseEntered
        teslim_et_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/odunc-al2.png")));
        jButton_teslim_et.setForeground(Color.white);
        jButton_teslim_et.setBackground(new Color(153,0,153));
    }//GEN-LAST:event_jButton_teslim_etMouseEntered

    private void jButton_teslim_etMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_teslim_etMouseExited
        teslim_et_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/odunc-al.png")));
        jButton_teslim_et.setForeground(new Color(0,0,0));
        jButton_teslim_et.setBackground(Color.orange);
    }//GEN-LAST:event_jButton_teslim_etMouseExited

    private void kapatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapatMouseEntered
        kapat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/kapat2.png")));
    }//GEN-LAST:event_kapatMouseEntered

    private void kapatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapatMouseExited
        kapat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/kapat.png")));
    }//GEN-LAST:event_kapatMouseExited

    private void kucultMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kucultMouseEntered
        kucult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/kucult2.png")));
    }//GEN-LAST:event_kucultMouseEntered

    private void kucultMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kucultMouseExited
        kucult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/kucult.png")));
    }//GEN-LAST:event_kucultMouseExited

    private void kapatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapatMouseClicked
        System.exit(0);
    }//GEN-LAST:event_kapatMouseClicked

    private void kucultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kucultMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_kucultMouseClicked

    private void jButton_kitap_ekleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_kitap_ekleMouseClicked
        Kitap_ekle form = new Kitap_ekle();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton_kitap_ekleMouseClicked

    private void jButton_kitaplarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_kitaplarMouseClicked
        Kitap_Goruntule form = new Kitap_Goruntule();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton_kitaplarMouseClicked

    private void jButton_odunc_alMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_odunc_alMouseClicked
        Odunc_al form = new Odunc_al();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton_odunc_alMouseClicked

    private void jButton_teslim_etActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_teslim_etActionPerformed
        
    }//GEN-LAST:event_jButton_teslim_etActionPerformed

    private void jButton_teslim_etMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_teslim_etMouseClicked
        Teslim_Al form = new Teslim_Al();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton_teslim_etMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Anasayfa().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_kitap_ekle;
    private javax.swing.JButton jButton_kitaplar;
    private javax.swing.JButton jButton_odunc_al;
    private javax.swing.JButton jButton_teslim_et;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel kapat;
    private javax.swing.JLabel kitaplar_img;
    private javax.swing.JLabel kucult;
    private javax.swing.JLabel odunc_al;
    private javax.swing.JLabel teslim_et_img;
    // End of variables declaration//GEN-END:variables
}
