/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sayfalar;

import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import javax.swing.JFrame;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Salih Degirmenci
 */
public class Kitap_ekle extends javax.swing.JFrame {

    /**
     * Creates new form Kitap_ekle
     */
    public Kitap_ekle() {
        initComponents();
        this.setLocationRelativeTo(null);
        jComboBox_Kategori.setSelectedItem("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Kitap_Adi = new javax.swing.JTextField();
        jTextField_Yazar_Adi = new javax.swing.JTextField();
        jTextField_Yayin_Evi = new javax.swing.JTextField();
        jTextField_Basim_Tarihi = new javax.swing.JTextField();
        jTextField_ISBN = new javax.swing.JTextField();
        jComboBox_Kategori = new javax.swing.JComboBox<>();
        jButton_Ekle = new javax.swing.JButton();
        HomePage_Icon = new javax.swing.JLabel();
        Kucult_icon = new javax.swing.JLabel();
        kapat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kitap Ekle");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel5)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Kitap Adı:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Yazar Adı:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Yayın Evi:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setText("Basım Tarihi:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setText("ISBN:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("Kategori:");

        jTextField_Kitap_Adi.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jTextField_Yazar_Adi.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jTextField_Yayin_Evi.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jTextField_Basim_Tarihi.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField_Basim_Tarihi.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_Basim_Tarihi.setText("30.12.2020");
        jTextField_Basim_Tarihi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_Basim_TarihiFocusGained(evt);
            }
        });
        jTextField_Basim_Tarihi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Basim_TarihiActionPerformed(evt);
            }
        });

        jTextField_ISBN.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField_ISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ISBNActionPerformed(evt);
            }
        });
        jTextField_ISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ISBNKeyTyped(evt);
            }
        });

        jComboBox_Kategori.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jComboBox_Kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Roman", "Şiir Kitabı", "Tarih Kitabı", "Hukuk Kitabı", "Felsefe Kitabı", "Dini Kitaplar", "Çocuk Kitapları", "Eğitici Kitaplar" }));
        jComboBox_Kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_KategoriActionPerformed(evt);
            }
        });

        jButton_Ekle.setBackground(new java.awt.Color(153, 0, 153));
        jButton_Ekle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_Ekle.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Ekle.setText("Ekle");
        jButton_Ekle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Ekle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_EkleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_EkleMouseExited(evt);
            }
        });
        jButton_Ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EkleActionPerformed(evt);
            }
        });

        HomePage_Icon.setToolTipText("ANAMENU");
        HomePage_Icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomePage_Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomePage_IconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomePage_IconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomePage_IconMouseExited(evt);
            }
        });

        Kucult_icon.setToolTipText("Simge Durumuna");
        Kucult_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kucult_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Kucult_iconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Kucult_iconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Kucult_iconMouseExited(evt);
            }
        });

        kapat.setToolTipText("KAPAT");
        kapat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kapat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kapatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kapatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kapatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(HomePage_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(Kucult_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Ekle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_Yazar_Adi, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(jTextField_Yayin_Evi, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(jTextField_Kitap_Adi, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(jTextField_Basim_Tarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_ISBN)
                                    .addComponent(jComboBox_Kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HomePage_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Kucult_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_Kitap_Adi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Yazar_Adi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_Yayin_Evi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_Basim_Tarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(60, 60, 60)
                .addComponent(jButton_Ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        HomePage_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/homepage-icon.png")));
        Kucult_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/kucult.png")));
        kapat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/kapat.png")));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Basim_TarihiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Basim_TarihiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Basim_TarihiActionPerformed

    private void HomePage_IconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePage_IconMouseEntered
        HomePage_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/homepage2-icon.png")));
    }//GEN-LAST:event_HomePage_IconMouseEntered

    private void HomePage_IconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePage_IconMouseExited
        HomePage_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/homepage-icon.png")));
    }//GEN-LAST:event_HomePage_IconMouseExited

    private void HomePage_IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePage_IconMouseClicked
        Anasayfa form = new Anasayfa();
                form.setVisible(true);
                form.pack();
                form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                //form.setLocationRelativeTo(null);
                this.dispose();
    }//GEN-LAST:event_HomePage_IconMouseClicked

    private void Kucult_iconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kucult_iconMouseEntered
        Kucult_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/kucult2.png")));
    }//GEN-LAST:event_Kucult_iconMouseEntered

    private void Kucult_iconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kucult_iconMouseExited
        Kucult_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/kucult.png")));
    }//GEN-LAST:event_Kucult_iconMouseExited

    private void Kucult_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kucult_iconMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_Kucult_iconMouseClicked

    private void kapatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapatMouseClicked
        System.exit(0);
    }//GEN-LAST:event_kapatMouseClicked

    private void kapatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapatMouseEntered
        kapat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/kapat2.png")));
    }//GEN-LAST:event_kapatMouseEntered

    private void kapatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapatMouseExited
        kapat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/kapat.png")));
    }//GEN-LAST:event_kapatMouseExited

    private void jComboBox_KategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_KategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_KategoriActionPerformed

    private void jTextField_ISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ISBNActionPerformed
       
    }//GEN-LAST:event_jTextField_ISBNActionPerformed

    private void jButton_EkleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_EkleMouseEntered
        jButton_Ekle.setBackground(Color.orange);
    }//GEN-LAST:event_jButton_EkleMouseEntered

    private void jButton_EkleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_EkleMouseExited
        jButton_Ekle.setBackground(new Color(153,0,153));
    }//GEN-LAST:event_jButton_EkleMouseExited

    private void jTextField_ISBNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ISBNKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_ISBNKeyTyped

    private void jButton_EkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EkleActionPerformed
        String Kitap_Adi = jTextField_Kitap_Adi.getText();
        String Yazar_Adi = jTextField_Yazar_Adi.getText();
        String Yayin_Evi = jTextField_Yayin_Evi.getText();
        String Basim_Tarihi = jTextField_Basim_Tarihi.getText();
        String ISBN = jTextField_ISBN.getText();
        String Kategori = (String)jComboBox_Kategori.getSelectedItem();
        Integer Durum = 1;
        
        
        if(Kontrol_Fields()){
            if(!Ayni_Mi(Kitap_Adi,Yazar_Adi)){
                PreparedStatement ps;
                ResultSet rs;
                String KaydetmeQuery = "INSERT INTO `tbl_kitaplar`(`Kitap_Adi`, `Yazar_Adi`, `Yayin_Evi`, `Basim_Tarihi`, `ISBN`, `Kategori`, `Durum`) VALUES (?,?,?,?,?,?,?)";
                
                try {
                    ps=(PreparedStatement) My_CNX.getConnection().prepareStatement(KaydetmeQuery);
                    ps.setString(1, Kitap_Adi);
                    ps.setString(2, Yazar_Adi);
                    ps.setString(3, Yayin_Evi);
                    ps.setString(4, Basim_Tarihi);
                    ps.setString(5, ISBN);
                    ps.setString(6, Kategori);
                    ps.setInt(7, Durum);
                    
                    if(ps.executeUpdate() != 0){
                        JOptionPane.showMessageDialog(null, "Kayıt Başarılı!");
                        AlanSil();
                    }else{
                        JOptionPane.showMessageDialog(null, "Hata: Bilgilerinizi Kontrol Edin");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Kitap_ekle.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton_EkleActionPerformed

    private void jTextField_Basim_TarihiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Basim_TarihiFocusGained
        jTextField_Basim_Tarihi.setText("");
        jTextField_Basim_Tarihi.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_jTextField_Basim_TarihiFocusGained

    
    //Fieldların dolululuğunu kontrol etme
    public boolean Kontrol_Fields(){
        String Kitap_Adi = jTextField_Kitap_Adi.getText();
        String Yazar_Adi = jTextField_Yazar_Adi.getText();
        String Yayin_Evi = jTextField_Yayin_Evi.getText();
        String Basim_Tarihi = jTextField_Basim_Tarihi.getText();
        String ISBN = jTextField_ISBN.getText();
        String Kategori = (String)jComboBox_Kategori.getSelectedItem();
        
        if (Kitap_Adi.trim().equals("") || Yazar_Adi.trim().equals("") || Yayin_Evi.trim().equals("")
                || Basim_Tarihi.trim().equals("") || ISBN.trim().equals("") || Kategori.equals("")) {
            JOptionPane.showMessageDialog(null,"Bir ya da birden fazla alan boş!","Eksik Bilgi!",2);
            return false;
        }else{
            return true;
        }
    }
    
    public boolean Ayni_Mi(String Kitap_Adi,String Yazar_Adi){
        PreparedStatement st;
        ResultSet rs;
        boolean Kitap_var_mi=false;
        
        String query = "SELECT * FROM `tbl_kitaplar` WHERE `Kitap_Adi` = ? and `Yazar_Adi` = ?";
        
        try {
            st = (PreparedStatement) My_CNX.getConnection().prepareStatement(query);
            st.setString(1, Kitap_Adi);
            st.setString(2, Yazar_Adi);
            rs = st.executeQuery();
            if(rs.next()){
                Kitap_var_mi=true;
                JOptionPane.showMessageDialog(null,"Kitap Zaten Kayıtlı!","Tekrar Eden Kayıt!",2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Kitap_ekle.class.getName()).log(Level.SEVERE, null, ex);
        }
        return Kitap_var_mi;
    }
    public void AlanSil(){
        jTextField_Kitap_Adi.setText("");
        jTextField_Yazar_Adi.setText("");
        jTextField_Kitap_Adi.setText("");
        jTextField_Basim_Tarihi.setText("30.12.2020");
        jTextField_Basim_Tarihi.setForeground(new Color(204,204,204));
        jTextField_ISBN.setText("");
        jTextField_Yayin_Evi.setText("");
        jComboBox_Kategori.setSelectedItem("Roman");
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kitap_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kitap_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kitap_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kitap_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kitap_ekle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HomePage_Icon;
    private javax.swing.JLabel Kucult_icon;
    private javax.swing.JButton jButton_Ekle;
    private javax.swing.JComboBox<String> jComboBox_Kategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField_Basim_Tarihi;
    private javax.swing.JTextField jTextField_ISBN;
    private javax.swing.JTextField jTextField_Kitap_Adi;
    private javax.swing.JTextField jTextField_Yayin_Evi;
    private javax.swing.JTextField jTextField_Yazar_Adi;
    private javax.swing.JLabel kapat;
    // End of variables declaration//GEN-END:variables
}
