/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sayfalar;

import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Salih Degirmenci
 */
public class Kitap_Goruntule extends javax.swing.JFrame {

    /**
     * Creates new form Kitap_Goruntule
     */
    public Kitap_Goruntule() {
        initComponents();
        this.setLocationRelativeTo(null);
        kitaplariGoster();
    }
    
    public ArrayList<Kitaplar> Kitaplari_Al(){
        ArrayList<Kitaplar> kitapListesi = new ArrayList<>();
        PreparedStatement st;
        ResultSet rs;
        String dataBaseConError = "Bir Hata Oluştu";
        //Get Available Books From DB (query)
        //Default query
        String query = "SELECT `Kitap_Adi`, `Yazar_Adi`, `Yayin_Evi`, `Basim_Tarihi`, `ISBN`, `Kategori` FROM `tbl_kitaplar` WHERE `Durum` = 1";
        //If user select a category
        if(!((String)jComboBox_kategoriSec.getSelectedItem()).equals("Tümü")){
            String secim = (String)jComboBox_kategoriSec.getSelectedItem();
         query = "SELECT `Kitap_Adi`, `Yazar_Adi`, `Yayin_Evi`, `Basim_Tarihi`, `ISBN`, `Kategori` FROM `tbl_kitaplar` WHERE `Durum` = 1 and `Kategori` ='"+secim+"'";   
        }
        try {
            st = (PreparedStatement) My_CNX.getConnection().prepareStatement(query);
            rs= st.executeQuery(query);
            Kitaplar kitaplar;
            //Gelen Tüm verileri almak için
            while (rs.next()) {
                kitaplar= new Kitaplar(rs.getString("Kitap_Adi"),rs.getString("Yazar_Adi"),rs.getString("Yayin_Evi"),rs.getString("Basim_Tarihi"),rs.getString("ISBN"),rs.getString("Kategori"));
                kitapListesi.add(kitaplar);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Kitap_Goruntule.class.getName()).log(Level.SEVERE, null, ex);
        }
        return kitapListesi;
    }
    public void kitaplariGoster(){
        ArrayList<Kitaplar> liste = Kitaplari_Al();//An ArrayList for all books
        DefaultTableModel model = (DefaultTableModel) jTable_kitaplarTablosu.getModel();
        Object[] satir = new Object[6];
        for (int i = 0; i < liste.size(); i++) {
            satir[0] = liste.get(i).Kitap_Adi();
            satir[1] = liste.get(i).Yazar_Adi();
            satir[2] = liste.get(i).Yayin_Evi();
            satir[3] = liste.get(i).Basim_Tarihi();
            satir[4] = liste.get(i).ISBN();
            satir[5] = liste.get(i).Kategori();
            model.addRow(satir);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        kapat = new javax.swing.JLabel();
        Kucult_icon = new javax.swing.JLabel();
        HomePage_Icon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_kategoriSec = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_kitaplarTablosu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        kapat.setToolTipText("KAPAT");
        kapat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kapat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kapatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kapatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kapatMouseExited(evt);
            }
        });

        Kucult_icon.setToolTipText("Simge Durumuna");
        Kucult_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kucult_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Kucult_iconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Kucult_iconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Kucult_iconMouseExited(evt);
            }
        });

        HomePage_Icon.setToolTipText("ANAMENU");
        HomePage_Icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomePage_Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomePage_IconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomePage_IconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomePage_IconMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Görüntülemek İstediğiniz Kategoriyi Seçin:");

        jComboBox_kategoriSec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox_kategoriSec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tümü", "Roman", "Şiir Kitabı", "Tarih Kitabı", "Hukuk Kitabı", "Felsefe Kitabı", "Dini Kitaplar", "Çocuk Kitapları", "Eğitici Kitaplar" }));
        jComboBox_kategoriSec.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox_kategoriSecPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomePage_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox_kategoriSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addComponent(Kucult_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HomePage_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox_kategoriSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Kucult_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        kapat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/kapat.png")));
        Kucult_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/kucult.png")));
        HomePage_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/homepage-icon.png")));

        jTable_kitaplarTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kitap Adı", "Yazar Adı", "Yayın Evi", "Basım Tarihi", "ISBN", "Kategori"
            }
        ));
        jScrollPane1.setViewportView(jTable_kitaplarTablosu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kapatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapatMouseClicked
        System.exit(0);
    }//GEN-LAST:event_kapatMouseClicked

    private void kapatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapatMouseEntered
        kapat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/kapat2.png")));
    }//GEN-LAST:event_kapatMouseEntered

    private void kapatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapatMouseExited
        kapat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/kapat.png")));
    }//GEN-LAST:event_kapatMouseExited

    private void Kucult_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kucult_iconMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_Kucult_iconMouseClicked

    private void Kucult_iconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kucult_iconMouseEntered
        Kucult_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/kucult2.png")));
    }//GEN-LAST:event_Kucult_iconMouseEntered

    private void Kucult_iconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kucult_iconMouseExited
        Kucult_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/kucult.png")));
    }//GEN-LAST:event_Kucult_iconMouseExited

    private void HomePage_IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePage_IconMouseClicked
        Anasayfa form = new Anasayfa();
        form.setVisible(true);
        form.pack();
        form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_HomePage_IconMouseClicked

    private void HomePage_IconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePage_IconMouseEntered
        HomePage_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/homepage2-icon.png")));
    }//GEN-LAST:event_HomePage_IconMouseEntered

    private void HomePage_IconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePage_IconMouseExited
        HomePage_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/homepage-icon.png")));
    }//GEN-LAST:event_HomePage_IconMouseExited

    private void jComboBox_kategoriSecPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox_kategoriSecPopupMenuWillBecomeInvisible
        DefaultTableModel model = (DefaultTableModel) jTable_kitaplarTablosu.getModel();
        model.setRowCount(0);
        kitaplariGoster();
    }//GEN-LAST:event_jComboBox_kategoriSecPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kitap_Goruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kitap_Goruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kitap_Goruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kitap_Goruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kitap_Goruntule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HomePage_Icon;
    private javax.swing.JLabel Kucult_icon;
    private javax.swing.JComboBox<String> jComboBox_kategoriSec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_kitaplarTablosu;
    private javax.swing.JLabel kapat;
    // End of variables declaration//GEN-END:variables
}
